#!/usr/bin/env python3
"""Focused fail-closed checks using an already built helper prefix; no C compile.

python3 scripts/fixtures/sqlite-build/test-inputs.py --archive FILE --prefix PREFIX
Run prepare-sqlite-build.sh once first. Temporary negative inputs stay under the
same owned parent and are removed; the original prefix/archive are read-only.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--archive', required=True, type=Path)
    parser.add_argument('--prefix', required=True, type=Path)
    args = parser.parse_args()
    helper = Path(__file__).resolve().parents[2] / 'prepare-sqlite-build.sh'
    manifest = json.loads((args.prefix / 'manifest.json').read_text())
    target = manifest['inputs']['target']

    def invoke(archive, prefix, error=None, selected_target=target):
        command = ['bash', str(helper), '--archive', str(archive), '--prefix',
                   str(prefix), '--target', selected_target]
        result = subprocess.run(command, capture_output=True, text=True, timeout=30)
        print(json.dumps({'command': command, 'exit': result.returncode,
                          'stdout': result.stdout, 'stderr': result.stderr}))
        if error:
            assert result.returncode != 0, 'negative input unexpectedly succeeded'
            assert error in result.stderr, result.stderr
            assert not result.stdout, 'failure exported usable build environment'
            assert '-c ' not in result.stderr, 'rejected cache triggered a compile'
            assert '.build-' not in result.stderr, 'rejected cache triggered a replacement build'
        else:
            assert result.returncode == 0, result.stderr
            assert 'Verified same-input SQLite build reuse' in result.stderr
            assert 'SQLITE3_NO_PKG_CONFIG=1' in result.stdout
            assert 'SQLITE3_STATIC=1' in result.stdout
            assert '-c ' not in result.stderr, 'reuse compiled rather than verified'

    invoke(args.archive, args.prefix)
    with tempfile.TemporaryDirectory(prefix='sqlite-input-negative-',
                                     dir=args.prefix.parent) as directory:
        root = Path(directory)
        corrupt = root / 'corrupt.zip'
        data = bytearray(args.archive.read_bytes())
        data[len(data) // 2] ^= 1
        corrupt.write_bytes(data)
        unused = root / 'unused'
        invoke(corrupt, unused, 'archive SHA-256 mismatch')
        assert not unused.exists()
        invoke(args.archive, unused, 'matching native Linux GNU',
               selected_target='aarch64-unknown-linux-gnu' if target.startswith('x86')
               else 'x86_64-unknown-linux-gnu')
        assert not unused.exists()
        unknown = root / 'unknown'
        unknown.mkdir()
        sentinel = unknown / 'KEEP'
        sentinel.write_text('not generated by helper')
        invoke(args.archive, unknown, 'manifest.json')
        assert list(unknown.iterdir()) == [sentinel]
        assert sentinel.read_text() == 'not generated by helper'
        symlink = root / 'symlink'
        symlink.symlink_to(unknown, target_is_directory=True)
        invoke(args.archive, symlink, 'symlink path refused')
        locked = root / 'locked'
        lock = root / 'locked.lock'
        lock.write_text('another writer')
        invoke(args.archive, locked, 'File exists')
        assert lock.read_text() == 'another writer'
        assert not locked.exists()
        for name, expected in [('missing-lib', 'output inventory differs'),
                               ('tampered-lib', 'output hash/type mismatch'),
                               ('stale-flags', 'input identity differs')]:
            copy = root / name
            shutil.copytree(args.prefix, copy)
            library = copy / 'lib/libsqlite3.a'
            if name == 'missing-lib':
                library.unlink()
            elif name == 'tampered-lib':
                with library.open('ab') as stream:
                    stream.write(b'tampered')
            else:
                stale = json.loads((copy / 'manifest.json').read_text())
                stale['inputs']['flags'].append('-DSQLITE_THREADSAFE=0')
                (copy / 'manifest.json').write_text(json.dumps(stale))
            invoke(args.archive, copy, expected)
            if name == 'missing-lib':
                assert not library.exists(), 'missing archive silently replaced/fell back'
        # Independent B1 repro: a valid relocated cache loses both the archive
        # and its manifest entry, while its linked smoke still embeds SQLite.
        copy = root / 'missing-lib-and-entry'
        shutil.copytree(args.prefix, copy)
        relocated = json.loads((copy / 'manifest.json').read_text())
        env_text = ''.join(f'export {k}={shlex.quote(v)}\n' for k, v in {
            'SQLITE3_LIB_DIR': str(copy / 'lib'),
            'SQLITE3_INCLUDE_DIR': str(copy / 'include'),
            'SQLITE3_STATIC': '1', 'SQLITE3_NO_PKG_CONFIG': '1'}.items())
        (copy / 'env.sh').write_text(env_text)
        relocated['outputs']['env.sh'] = hashlib.sha256(env_text.encode()).hexdigest()
        library = copy / 'lib/libsqlite3.a'
        library.unlink()
        del relocated['outputs']['lib/libsqlite3.a']
        (copy / 'manifest.json').write_text(json.dumps(relocated))
        before = {str(p.relative_to(copy)): p.read_bytes()
                  for p in copy.rglob('*') if p.is_file()}
        siblings = set(root.iterdir())
        invoke(args.archive, copy, 'required output inventory differs')
        assert not library.exists(), 'missing archive silently replaced/fell back'
        assert set(root.iterdir()) == siblings, 'rejection left a lock/replacement stage'
        assert {str(p.relative_to(copy)): p.read_bytes()
                for p in copy.rglob('*') if p.is_file()} == before, 'rejection changed cache'
    print('PASS: same-input actual smoke reuse and 9 fail-closed input/cache controls')


if __name__ == '__main__':
    main()
