// Data steps of scripts/perf/perf-inner.sh; the shell keeps only process
// orchestration.
//
//   DB_NAME=.. ROLE_NAME=.. ROLE_PASSWORD=.. TEST_DATABASE_URL=.. bun perf-inner.ts db-urls
//     prints the admin URL and the app-role URL, one per line
//   bun perf-inner.ts run-json <file> <postgres-server-version>
//     writes the run metadata JSON
//
// Secrets travel through the environment and stdout only, never argv or stderr.
import { writeFileSync } from "node:fs";

export class Refusal extends Error {}

const GENERATED = /^[0-9a-z_]+$/;

// Admin URL: the admin URL text with only its path replaced. App URL: the same
// host and port with the app role. The URL parser decides validity (port
// range, IPv6 literal, forbidden host characters); the checks around it refuse
// what it would otherwise accept or rewrite.
export function buildDbUrls(
  adminUrl: string,
  db: string,
  role: string,
  password: string,
): { admin: string; app: string } {
  for (const [name, value] of [
    ["DB_NAME", db],
    ["ROLE_NAME", role],
    ["ROLE_PASSWORD", password],
  ] as const) {
    // Generated by the caller; anything else would need percent-encoding.
    if (!GENERATED.test(value)) throw new Refusal(`${name} must match ${GENERATED.source}`);
  }
  // The parser strips or percent-encodes these instead of refusing them.
  if (!/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\/[!-~]*$/.test(adminUrl)) {
    throw new Refusal("TEST_DATABASE_URL is not a printable ASCII URL");
  }
  const schemeEnd = adminUrl.indexOf("://") + 3;
  const rest = adminUrl.slice(schemeEnd);
  const authority = rest.slice(0, rest.search(/[/?#]|$/));
  const userinfoEnd = authority.lastIndexOf("@");
  if (/[[\]]/.test(authority.slice(0, Math.max(userinfoEnd, 0)))) {
    throw new Refusal("TEST_DATABASE_URL has a bracket in its userinfo");
  }
  let parsed: URL;
  try {
    parsed = new URL(adminUrl);
  } catch {
    throw new Refusal("TEST_DATABASE_URL is not a valid URL");
  }
  if (parsed.port === "0") throw new Refusal("TEST_DATABASE_URL has a port outside 1-65535");
  const tail = rest.slice(authority.length);
  const suffix = tail.slice(tail.search(/[?#]|$/));
  const host = parsed.hostname.toLowerCase() || "127.0.0.1";
  return {
    admin: `${adminUrl.slice(0, schemeEnd)}${authority}/${db}${suffix}`,
    app: `postgres://${role}:${password}@${host}:${parsed.port || "5432"}/${db}`,
  };
}

export function utcTimestamp(epochMs: number): string {
  const micros = Math.floor(epochMs * 1000) % 1_000_000;
  const seconds = new Date(Math.floor(epochMs / 1000) * 1000).toISOString().slice(0, 19);
  return `${seconds}.${String(micros).padStart(6, "0")}+00:00`;
}

export function renderRunJson(startedAt: string, pgVersion: string): string {
  // Bytes outside ASCII arrive in an unknown encoding; refuse instead of guessing.
  if (/\P{ASCII}/u.test(pgVersion)) throw new Refusal("server_version is not ASCII");
  const record = {
    dataset_run_started: startedAt,
    postgres_server_version: pgVersion,
    network: "loopback 127.0.0.1",
    server: "release fvoci-server (source build)",
  };
  return JSON.stringify(record, null, 1);
}

function main(argv: string[], env: NodeJS.ProcessEnv): void {
  const [command, ...args] = argv;
  if (command === "db-urls" && args.length === 0) {
    const urls = buildDbUrls(
      env.TEST_DATABASE_URL ?? "",
      env.DB_NAME ?? "",
      env.ROLE_NAME ?? "",
      env.ROLE_PASSWORD ?? "",
    );
    process.stdout.write(`${urls.admin}\n${urls.app}\n`);
  } else if (command === "run-json" && args.length === 2) {
    const [file = "", pgVersion = ""] = args;
    const now = performance.timeOrigin + performance.now();
    writeFileSync(file, renderRunJson(utcTimestamp(now), pgVersion));
  } else {
    throw new Refusal("usage: perf-inner.ts db-urls | run-json <file> <server-version>");
  }
}

if (import.meta.main) {
  try {
    main(process.argv.slice(2), process.env);
  } catch (error) {
    if (!(error instanceof Refusal)) throw error;
    console.error(error.message);
    process.exit(1);
  }
}
