//! Rust Tiptap → Yjs seed vs the TS `tiptapJsonToYUpdate` oracle
//! (`compat/fixtures/yjs-seed`, regenerated by `scripts/regen-yjs-seed-oracle.sh`).
//!
//! Byte equality is not required (client ids / clocks differ). Both updates are
//! decoded with Yrs (Utf16, skip_gc) and compared as trees: child kinds, element
//! tags, attrs (null/ychange dropped), XmlText delta inserts with decoded mark
//! names and attr contents, then `Project` output.

#![cfg(feature = "worker")]

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use collab_engine::engine::new_doc;
use collab_engine::outcome::EngineStatus;
use collab_engine::protocol::Request;
use collab_engine::seed::{tiptap_to_yjs_update, AttrDefault, SCHEMA_MARKS, SCHEMA_NODES};
use collab_engine::{CollabEngine, EngineSession, Limits, SpawnRequest};
use serde_json::{json, Value};
use yrs::types::text::YChange;
use yrs::updates::decoder::Decode;
use yrs::{Any, Out, ReadTxn, Text, Transact, Update, Xml, XmlFragment, XmlOut};

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn seed_dir() -> PathBuf {
    repo().join("compat/fixtures/yjs-seed")
}

fn read_json(path: &Path) -> Value {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

struct Case {
    name: String,
    input: Value,
    /// `Ok(update)` or `Err(helper code)`.
    oracle: Result<Vec<u8>, String>,
}

fn cases() -> Vec<Case> {
    let mut out = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(seed_dir().join("oracle"))
        .expect("oracle dir")
        .map(|e| e.expect("entry").path())
        .collect();
    entries.sort();
    for path in entries {
        let file = path.file_name().unwrap().to_str().unwrap().to_string();
        let (name, oracle) = if let Some(name) = file.strip_suffix(".yupdate") {
            let b64 = fs::read_to_string(&path).expect("yupdate");
            let bytes = collab_engine::b64::decode(b64.trim()).expect("base64");
            (name.to_string(), Ok(bytes))
        } else if let Some(name) = file.strip_suffix(".error") {
            (
                name.to_string(),
                Err(fs::read_to_string(&path).expect("error")),
            )
        } else {
            panic!("unexpected oracle file {file}");
        };
        let input = match name.strip_prefix("md-") {
            Some(md) => repo().join(format!("compat/fixtures/markdown-oracle/{md}.json")),
            None => seed_dir().join(format!("cases/{name}.json")),
        };
        out.push(Case {
            name,
            input: read_json(&input),
            oracle,
        });
    }
    assert!(
        out.len() >= 66,
        "expected the full corpus, got {}",
        out.len()
    );
    out
}

#[derive(Debug, PartialEq)]
enum Tree {
    Element {
        tag: String,
        attrs: BTreeMap<String, Value>,
        children: Vec<Tree>,
    },
    /// XmlText delta: `(insert, {decoded mark name: attrs})`.
    Text(Vec<(String, BTreeMap<String, Value>)>),
}

fn any_json(any: &Any) -> Value {
    match any {
        Any::Null | Any::Undefined => Value::Null,
        Any::Bool(b) => Value::Bool(*b),
        Any::Number(n) => json!(n.as_f64().expect("finite")),
        Any::String(s) => Value::String(s.to_string()),
        Any::Buffer(_) => panic!("buffer attr"),
        Any::Array(items) => Value::Array(items.iter().map(any_json).collect()),
        Any::Map(map) => Value::Object(map.iter().map(|(k, v)| (k.clone(), any_json(v))).collect()),
    }
}

fn out_any(out: Out) -> Any {
    match out {
        Out::Any(any) => any,
        other => panic!("non-Any value {other:?}"),
    }
}

fn tree_children<T: ReadTxn>(txn: &T, parent: &impl XmlFragment) -> Vec<Tree> {
    let mut out = Vec::new();
    for i in 0..parent.len(txn) {
        match parent.get(txn, i).expect("child") {
            XmlOut::Element(el) => {
                let mut attrs = BTreeMap::new();
                for (k, v) in el.attributes(txn) {
                    let any = out_any(v);
                    if k != "ychange" && !matches!(any, Any::Null | Any::Undefined) {
                        attrs.insert(k.to_string(), any_json(&any));
                    }
                }
                out.push(Tree::Element {
                    tag: el.tag().to_string(),
                    attrs,
                    children: tree_children(txn, &el),
                });
            }
            XmlOut::Text(text) => {
                let mut runs = Vec::new();
                for diff in text.diff(txn, YChange::identity) {
                    let Out::Any(Any::String(insert)) = diff.insert else {
                        panic!("non-string insert");
                    };
                    let mut marks = BTreeMap::new();
                    for (k, v) in diff.attributes.iter().flat_map(|a| a.iter()) {
                        if k.as_ref() == "ychange" {
                            continue;
                        }
                        let name = yattr2markname(k);
                        assert!(
                            marks.insert(name.to_string(), any_json(v)).is_none(),
                            "duplicate mark {name}"
                        );
                    }
                    runs.push((insert.to_string(), marks));
                }
                out.push(Tree::Text(runs));
            }
            XmlOut::Fragment(_) => panic!("nested fragment"),
        }
    }
    out
}

/// y-tiptap `hashedMarkNameRegex = /(.*)(--[a-zA-Z0-9+/=]{8})$/`.
fn yattr2markname(name: &str) -> &str {
    let b = name.as_bytes();
    if b.len() >= 10 && &b[b.len() - 10..b.len() - 8] == b"--" {
        let suffix = &b[b.len() - 8..];
        if suffix
            .iter()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, b'+' | b'/' | b'='))
        {
            return &name[..name.len() - 10];
        }
    }
    name
}

fn tree_of(update: &[u8]) -> Vec<Tree> {
    let doc = new_doc();
    doc.transact_mut()
        .apply_update(Update::decode_v1(update).expect("decode"))
        .expect("apply");
    let txn = doc.transact();
    assert!(!txn.has_missing_updates());
    match txn.get_xml_fragment("prosemirror") {
        Some(frag) => tree_children(&txn, &frag),
        None => Vec::new(),
    }
}

fn project_of(update: &[u8]) -> Value {
    let mut engine = CollabEngine::new(Limits::for_tests());
    let load = engine.handle(&Request::Load {
        snapshot_b64: Some(update.to_vec()),
        tail_b64: Vec::new(),
        encoding: 1,
    });
    assert!(load.is_applied_ok(), "{load:?}");
    match engine.handle(&Request::Project { encoding: 1 }) {
        EngineStatus::Ok {
            content_json: Some(json),
            ..
        } => sort_marks(json),
        other => panic!("project: {other:?}"),
    }
}

fn sort_marks(value: Value) -> Value {
    match value {
        Value::Array(items) => Value::Array(items.into_iter().map(sort_marks).collect()),
        Value::Object(obj) => Value::Object(
            obj.into_iter()
                .map(|(k, v)| {
                    let v = match (k.as_str(), v) {
                        ("marks", Value::Array(mut marks)) => {
                            marks.sort_by_key(|m| m.to_string());
                            Value::Array(marks)
                        }
                        (_, v) => sort_marks(v),
                    };
                    (k, v)
                })
                .collect(),
        ),
        other => other,
    }
}

#[test]
fn rust_seed_matches_ts_oracle_tree() {
    let limits = Limits::for_tests();
    let (mut ok, mut refused) = (0, 0);
    for case in cases() {
        let rust = tiptap_to_yjs_update(&case.input, &limits);
        match (&case.oracle, rust) {
            (Ok(oracle), Ok(rust)) => {
                assert_eq!(tree_of(&rust), tree_of(oracle), "{}: tree", case.name);
                assert_eq!(
                    project_of(&rust),
                    project_of(oracle),
                    "{}: project",
                    case.name
                );
                ok += 1;
            }
            (Err(code), Err(EngineStatus::Malformed { .. })) => {
                assert_eq!(code, "invalid_input", "{}", case.name);
                refused += 1;
            }
            (oracle, rust) => panic!(
                "{}: oracle {:?} vs rust {:?}",
                case.name,
                oracle.as_ref().map(|b| b.len()),
                rust.map(|b| b.len())
            ),
        }
    }
    eprintln!("seed compat: {ok} equal trees, {refused} refused by both");
    assert!(ok >= 60 && refused == 3, "{ok} / {refused}");
}

fn spawn() -> EngineSession {
    EngineSession::spawn(SpawnRequest {
        engine_bin: PathBuf::from(env!("CARGO_BIN_EXE_collab-engine")),
        limits: Limits::for_tests(),
        slot_kind: collab_engine::process::ChildSlotKind::Primary,
        slot_wait: None,
        test_hang_ms: None,
        test_exit_after_read: None,
        test_close_stdout_hang_ms: None,
        test_exit_after_write: None,
    })
    .unwrap_or_else(|r| panic!("spawn: {:?}", r.outcome))
}

#[test]
fn child_seed_op_matches_in_process_writer() {
    let mut session = spawn();
    for case in cases() {
        let report = session.call(&Request::SeedFromTiptap {
            content_json: serde_json::to_string(&case.input).unwrap(),
            encoding: 1,
        });
        match (&case.oracle, report.outcome) {
            (
                Ok(oracle),
                EngineStatus::Ok {
                    update_b64: Some(b64),
                    applied: false,
                    ..
                },
            ) => {
                let bytes = collab_engine::b64::decode(&b64).expect("b64");
                assert_eq!(tree_of(&bytes), tree_of(oracle), "{}", case.name);
            }
            // A refused request ends the child session (process policy).
            (Err(_), EngineStatus::Malformed { .. }) => session = spawn(),
            (_, other) => panic!("{}: {other:?}", case.name),
        }
    }
}

#[test]
fn child_seed_refuses_oversized_json() {
    let mut session = spawn();
    let big = json!({"type": "doc", "content": [{"type": "paragraph", "content": [
        {"type": "text", "text": "x".repeat(1024 * 1024)}
    ]}]});
    let report = session.call(&Request::SeedFromTiptap {
        content_json: big.to_string(),
        encoding: 1,
    });
    assert!(
        matches!(
            report.outcome,
            EngineStatus::ResourceLimit {
                kind: collab_engine::LimitKind::Input,
                ..
            }
        ),
        "{:?}",
        report.outcome
    );
}

/// The Rust schema table equals the editor schema the oracle seeded with.
#[test]
fn schema_table_matches_editor_schema() {
    let schema = read_json(&seed_dir().join("schema.json"));
    let spec_json = |attrs: &[(&str, AttrDefault)]| -> Vec<Value> {
        attrs
            .iter()
            .map(|(name, d)| {
                let default = match d {
                    AttrDefault::Null => Value::Null,
                    AttrDefault::Str(s) => json!(s),
                    AttrDefault::Int(i) => json!(i),
                    AttrDefault::Bool(b) => json!(b),
                    AttrDefault::EmptyArray => json!([]),
                };
                json!({"name": name, "hasDefault": true, "default": default, "validate": null})
            })
            .collect()
    };
    let nodes: Vec<Value> = SCHEMA_NODES
        .iter()
        .map(|(name, attrs)| json!({"name": name, "attrs": spec_json(attrs)}))
        .collect();
    assert_eq!(Value::Array(nodes), schema["nodes"]);
    let marks: Vec<Value> = SCHEMA_MARKS
        .iter()
        .enumerate()
        .map(|(rank, (name, attrs))| {
            json!({"name": name, "rank": rank, "overlapping": false, "attrs": spec_json(attrs)})
        })
        .collect();
    assert_eq!(Value::Array(marks), schema["marks"]);
}
