import type { components } from "@/generated/api";

export type SetupInput = components["schemas"]["SetupBody"];
export type LoginInput = components["schemas"]["LoginBody"];
export type WorkspaceCreateInput = components["schemas"]["CreateWorkspaceBody"];
export type WorkspaceRenameInput = components["schemas"]["PatchWorkspaceBody"];
export type WorkspaceRole = "owner" | "admin" | "member" | "guest";
export type MemberOutput = components["schemas"]["MemberResponse"];
export type InvitationCreateInput = components["schemas"]["InvitationCreateBody"];
export type InvitationPublicOutput = components["schemas"]["InvitationPublicResponse"];
export type InvitationAcceptInput = components["schemas"]["InvitationAcceptBody"];
export type ApiTokenOutput = components["schemas"]["ApiTokenOutput"];
export type ApiTokenCreatedOutput = components["schemas"]["ApiTokenCreatedOutput"];
export type ApiTokenCreateInput = components["schemas"]["ApiTokenCreateBody"];
export type ApiTokenScope = NonNullable<ApiTokenCreateInput["scopes"]>[number];
export type WebhookOutput = components["schemas"]["WebhookOutput"];
export type WebhookCreatedOutput = components["schemas"]["WebhookCreatedOutput"];
export type WebhookCreateInput = components["schemas"]["WebhookCreateBody"];
export type GithubInstallOutput = components["schemas"]["GithubInstallOutput"];
export type GithubIssueLinkInput = components["schemas"]["GithubIssueLinkBody"];
export type SessionUserOutput = components["schemas"]["SessionUserOutput"];
export type IdentityOutput = components["schemas"]["IdentityOutput"];
export type ProviderOutput = components["schemas"]["ProviderOutput"];
export type PasswordChangeInput = components["schemas"]["PasswordChangeBody"];
export type WithdrawInput = components["schemas"]["WithdrawBody"];
export type ProfileNameInput = { givenName: string; familyName: string | null };
